package vistas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import procesos.conectaDB;

public class frmPrincipalE extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public frmPrincipalE( String apellidos) {
        initComponents();
        this.setLocationRelativeTo(null);
        txtSesion.setText(apellidos);
        con = conectaDB.conectaDB();
        RadioApellido.setSelected(true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupBusqueda = new javax.swing.ButtonGroup();
        txtSesion = new javax.swing.JLabel();
        lbBienvenida = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBusqueda = new javax.swing.JTable();
        btnNuevoPaciente = new javax.swing.JButton();
        RadioHistoria = new javax.swing.JRadioButton();
        RadioApellido = new javax.swing.JRadioButton();
        RadioNombres = new javax.swing.JRadioButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSesion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSesion.setText("---------");
        getContentPane().add(txtSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 10, 90, 20));

        lbBienvenida.setText("Bienvenido:");
        getContentPane().add(lbBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });
        getContentPane().add(txtBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 520, 30));

        TablaBusqueda = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        TablaBusqueda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Historia", "Apellidos", "Nombres"
            }
        ));
        TablaBusqueda.setFocusable(false);
        TablaBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaBusqueda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 520, 110));

        btnNuevoPaciente.setText("Nuevo Paciente");
        btnNuevoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        btnGroupBusqueda.add(RadioHistoria);
        RadioHistoria.setText("Historia");
        RadioHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(RadioHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        btnGroupBusqueda.add(RadioApellido);
        RadioApellido.setText("Apellidos");
        RadioApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(RadioApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        btnGroupBusqueda.add(RadioNombres);
        RadioNombres.setText("Nombres");
        RadioNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioNombresActionPerformed(evt);
            }
        });
        getContentPane().add(RadioNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoFinal600x350.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        Busqueda();       
    }//GEN-LAST:event_txtBusquedaKeyReleased
    private void Busqueda(){
            //convertir en mayusculas los datos que se ingresan 
        int Posicion = txtBusqueda.getCaretPosition();
        String busqueda = (txtBusqueda.getText()).toUpperCase();
        txtBusqueda.setText(busqueda);
        txtBusqueda.setCaretPosition(Posicion);
        
       //sql para realizar la busqueda predictiva 
       String sql="";
        if (RadioNombres.isSelected()) {
             sql= "Select historia,apellidos,nombres from paciente where nombres like ? and estado =1";
        }if(RadioHistoria.isSelected()){
             sql= "Select historia,apellidos,nombres from paciente where historia like ? and estado =1";
        }if (RadioApellido.isSelected()) {
             sql= "Select historia,apellidos,nombres from paciente where apellidos like ? and estado =1";
        }                
      try
      {
          pst=con.prepareStatement(sql);
          pst.setString(1,busqueda+"%");          
          rs= pst.executeQuery();
          TablaBusqueda.setModel(DbUtils.resultSetToTableModel(rs));
          
      }catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }
    private void btnNuevoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPacienteActionPerformed
        String apellidos = txtSesion.getText();
        frmNuevoPacienteE frm = new frmNuevoPacienteE(apellidos,"");
        frm.setVisible(true);
    }//GEN-LAST:event_btnNuevoPacienteActionPerformed

    private void TablaBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaBusquedaMouseClicked
        String apellidos = txtSesion.getText();          
        try{
                    int row= TablaBusqueda.getSelectedRow();
                    String table_click= TablaBusqueda.getModel().getValueAt(row, 0).toString();
                    String sql= "select * from paciente p\n" +
                                "where historia = '"+table_click+"'";
                    pst=con.prepareStatement(sql);
                    rs=  pst.executeQuery();
                    if(rs.next()){
                    //envio de informacion al formulario de paciente cuando se encuentra un paciente
                        String historia=rs.getString("historia");
                        frmNuevoPacienteE frm = new frmNuevoPacienteE(apellidos,historia);
                        frm.setVisible(true);                        
                        frm.NumeroHistoria.setText(historia);
                        frm.txtApellidos.setText(rs.getString("apellidos"));
                        frm.txtNombres.setText(rs.getString("nombres"));
                        frm.ComboBoxSexo.setSelectedItem(rs.getString("sexo"));
                        frm.ComboBoxGSanguineo.setSelectedItem(rs.getString("grup_san"));
                        frm.ComboBoxEstado.setSelectedItem(rs.getString("estad_civil"));
                        frm.txtEdad.setText(rs.getString("edad"));
                        frm.txtTelefono.setText(rs.getString("fono"));
                        frm.txtDireccion.setText(rs.getString("direccion"));
                        frm.txtCI.setText(rs.getString("cedula"));
                        frm.txtAntecedentesFamiliares.setText(rs.getString("antFamiliares"));
                        frm.txtAntecedentesPersonales.setText(rs.getString("antPersonales"));
                        //campo oculpo para la edicion de solo la historia
                        frm.valorParaModificarSoloLaHistoria.setText("1234");
                                                
                        frm.txtApellidos.setEnabled(false);
                        frm.txtNombres.setEnabled(false);
                        frm.ComboBoxSexo.setEnabled(false);
                        frm.ComboBoxGSanguineo.setEnabled(false);
                        frm.ComboBoxEstado.setEnabled(false);
                        frm.txtEdad.setEnabled(false);
                        frm.txtCI.setEnabled(false);
                        frm.txtTelefono.setEnabled(false);
                        frm.txtDireccion.setEnabled(false);
                        frm.txtAntecedentesFamiliares.setEnabled(false);
                        frm.txtAntecedentesPersonales.setEnabled(false);
                        frm.CheckBoxEditarDatosGenerales.setVisible(true);
                        
             
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_TablaBusquedaMouseClicked

    private void RadioHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioHistoriaActionPerformed
       Busqueda();
    }//GEN-LAST:event_RadioHistoriaActionPerformed

    private void RadioNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioNombresActionPerformed
       Busqueda();
    }//GEN-LAST:event_RadioNombresActionPerformed

    private void RadioApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioApellidoActionPerformed
       Busqueda();
    }//GEN-LAST:event_RadioApellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipalE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new frmPrincipalE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioApellido;
    private javax.swing.JRadioButton RadioHistoria;
    private javax.swing.JRadioButton RadioNombres;
    private javax.swing.JTable TablaBusqueda;
    private javax.swing.ButtonGroup btnGroupBusqueda;
    private javax.swing.JButton btnNuevoPaciente;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBienvenida;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JLabel txtSesion;
    // End of variables declaration//GEN-END:variables
}
